### ISSUE TITLE
When removing account it prompts an error

### ISSUE THREAD

**Issue by win20-official** [XielQs/mail.tm-api#1]
Hello,
So i created a temporary e-mail generator using your library but when you remove an e-mail it prompts w/ an error and it crashes.
This is the error:
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "This account no longer exists.".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
Thanks,
Windows 20 @win20-official

**Comment by XielQs** [comment]
Can you share the full code?

**Comment by win20-official** [comment]
Yes, but on a repo because github is weird on comments

**Comment by XielQs** [comment]
Okay no problem 👍🏻

**Comment by win20-official** [comment]
This is the code https://github.com/win20-official/YouGotMail/blob/main/index.js

**Comment by win20-official** [comment]
do you have nodemon?

**Comment by win20-official** [comment]
@gamerboytr

**Comment by XielQs** [comment]
yes

**Comment by win20-official** [comment]
for testing clone the repo i sent the code and then run `npm i --save` and after that `npm run start`

**Comment by win20-official** [comment]
in terminal/command prompt

**Comment by XielQs** [comment]
okay

**Comment by win20-official** [comment]
i forgot to add these lines,
updating the repo

**Comment by win20-official** [comment]
can you do git pull in your terminal

**Comment by XielQs** [comment]
Its working fine for me, can you send me a screenshot ?

**Comment by win20-official** [comment]
![image](https://user-images.githubusercontent.com/80408876/202269142-d3313b3b-d9f9-47d0-9bee-621b32c9e07f.png)
when i press the delete account it gives me the error

**Comment by win20-official** [comment]
*btw in polish it means delete account*

**Comment by win20-official** [comment]
when i refresh it gives that error
![image](https://user-images.githubusercontent.com/80408876/202269603-887365c2-0f9e-4365-be9d-973adcc7521e.png)

**Comment by win20-official** [comment]
i mean when i refresh the browser

**Comment by XielQs** [comment]
dude i really have no clue what is causing this error. Maybe it's because of Mail TM's api

**Comment by win20-official** [comment]
i think.

**Comment by XielQs** [comment]
I tried 30-35 times, but still I couldn't get any results :/

**Comment by XielQs** [comment]
sorry for the trouble

**Comment by win20-official** [comment]
i'm on node 16

**Comment by win20-official** [comment]
Btw, i updated it to node 18 *LTS*

**Comment by XielQs** [comment]
try using disableListening option to true
```js
Mail.setConfig({
  disableListening: true
});
```
