### ISSUE TITLE
Folder "Errors" should be "errors" in npm

### ISSUE THREAD

**Issue by digitalgopnik** [XielQs/mail.tm-api#2]
Thanks for this nice package. But unfortunately i got on tiny error, because of the folder-name.

![image](https://user-images.githubusercontent.com/2630316/221796585-ecba7453-e6b2-467d-9ba5-1015c709ff3e.png)

Can you please rename it in npm - like it's in the github-repo here?

Error is thrown because of:

![image](https://user-images.githubusercontent.com/2630316/221797348-08dc9fe8-4156-429f-a39e-8c9f88df3aa1.png)

![image](https://user-images.githubusercontent.com/2630316/221797296-dcb764b5-ea21-4bda-bd46-7c618d850870.png)

Kindly regards :slightly_smiling_face:

**Comment by XielQs** [comment]
Ohhhh, thanks dude 👍 i am going to fix it, yn some ts problems 😄

**Comment by XielQs** [comment]
Fixed man ❤️
