### ISSUE TITLE
httptoolkit !!!

### ISSUE THREAD

**Issue by listmen001** [XielQs/mail.tm-api#4]
Верни ее)
новая ошибка вышла!(
не очень приятная.
И снова не работает.

При запуске серый экран и надпись:
"No internet connection and file is not cached for file: /"

Как исправить?)

**Comment by XielQs** [comment]
HTTP Toolkit Pro Patcher has been officially shut down! You can restore or reinstall HTTP Toolkit if you want.

**Comment by listmen001** [comment]
> HTTP Toolkit Pro Patcher has been officially shut down! You can restore or reinstall HTTP Toolkit if you want.

I would like to continue using your patch!

**Comment by XielQs** [comment]
You can buy a [subscription](https://httptoolkit.com/pricing/) if you want to continue use pro features! But Pro Patcher shut down.
